(require 'psvn)
(require 'etags-select)

;; Single keystrokes
(global-set-key (kbd "M-9")                   'add-symbol-at-point-to-kill-ring)
(global-set-key (kbd "C-M-b")                 'backward-word)
(global-set-key (kbd "C-l")                   'c-find-other-file)
(global-set-key (kbd "S-<f7>")                'compile)
(global-set-key (kbd "M-'")                   'cycle-other-buffer)
(global-set-key (kbd "M-RET")                 'delete-other-windows)
(global-set-key (kbd "C-M-<return>")          'delete-window)
(global-set-key (kbd "<f5>")                  'programming-project-debug-binary)
(global-set-key (kbd "M-.")                   'etags-select-find-tag)
(global-set-key (kbd "<f8>")                  'exit-recursive-edit)
(global-set-key (kbd "M-l")                   'file-cache-find-file-on-line)
(global-set-key (kbd "M-+")                   'generic-enlarge-window)
(global-set-key (kbd "M--")                   'generic-shrink-window)
(global-set-key (kbd "<f9>")                  'gud-break)
(global-set-key (kbd "S-<f6>")                'gud-down)
(global-set-key (kbd "S-<f11>")               'gud-finish)
(global-set-key (kbd "<f10>")                 'gud-next)
(global-set-key (kbd "S-<f9>")                'gud-remove)
(global-set-key (kbd "<f11>")                 'gud-step)
(global-set-key (kbd "S-<f8>")                'gud-stop-subjob)
(global-set-key (kbd "<f6>")                  'gud-up)  
(global-set-key (kbd "C-o")                   'ido-switch-buffer)
(global-set-key (kbd "C-M-z")                 'highlight-symbol-prev-auto-on)
(global-set-key (kbd "C-M-c")                 'highlight-symbol-next-auto-on)
(global-set-key (kbd "C-M-d")                 'kill-word)
(global-set-key (kbd "M-0")                   'line-to-top-of-window)
(global-set-key (kbd "M-I")                   'message-and-kill-add-buffer-file-name)
(global-set-key (kbd "C-M-p")                 'next-buffer)
(global-set-key (kbd "<f4>")                  'next-error)
(global-set-key (kbd "C-S-n")                 'next-six-lines)
(global-set-key (kbd "C-M-f")                 'next-word)
(global-set-key (kbd "C-M-n")                 'previous-buffer)
(global-set-key (kbd "S-<f4>")                'previous-error)
(global-set-key (kbd "C-S-p")                 'previous-six-lines)
(global-set-key (kbd "M-u")                   'programming-project-uncrustify-region)
(global-set-key (kbd "<f7>")                  'recompile)

;; C-c keystrokes
(global-set-key (kbd "C-c s")                 'highlight-symbol-at-point)
(global-set-key (kbd "C-c i")                 'browse-kill-ring)
(global-set-key (kbd "C-c <backspace>")       'c-hungry-delete-backwards)
(global-set-key (kbd "C-c C-d")               'c-hungry-delete-forward)
(global-set-key (kbd "C-c d")                 'downcase-word)
(global-set-key (kbd "C-c p")                 'programming-project-edit-current-project-file)
(global-set-key (kbd "C-c l")                 'simple-project-management-load-project)
(global-set-key (kbd "C-c e")                 'simple-project-management-create-project)
(global-set-key (kbd "C-c f")                 'file-cache-add-or-delete-this-file)
(global-set-key (kbd "C-c o")                 'file-cache-ido-find-file)
(global-set-key (kbd "C-c z")                 'file-cache-files-matching-with-mode)
(global-set-key (kbd "C-c <f12>")             'find-file-dot-emacs)
(global-set-key (kbd "C-c c")                 'goto-scratch-buffer)
(global-set-key (kbd "C-c j")                 'programming-project-grep-frontend)
(global-set-key (kbd "C-c k")                 'kill-current-buffer)
(global-set-key (kbd "C-c C-<tab>")           'lisp-complete-symbol)
(global-set-key (kbd "C-c q")                 'longlines-mode)
(global-set-key (kbd "C-c v")                 'programming-project-svn-status-current-source-root)
(global-set-key (kbd "C-c r")                 'rename-symbol)
(global-set-key (kbd "C-c h")                 'shell)
(global-set-key (kbd "C-c b")                 'svn-status-blame)
(global-set-key (kbd "C-c u")                 'upcase-word)
(global-set-key (kbd "C-c w")                 'whitespace-mode)

;; Ignored keystrokes
(global-set-key (kbd "C-z")                   'ignore)
(global-set-key (kbd "C-h C-c")               'ignore)

;; Override some local keymaps
(add-hook 'c-mode-hook            '(lambda () (local-set-key   (kbd "M-q") 'fill-paragraph)))

;; Unset some local keys
(add-hook 'svn-status-mode-hook   '(lambda () (local-unset-key (kbd "C-o"))))
(add-hook 'diff-mode-hook         '(lambda () (local-unset-key (kbd "M-RET"))))
(add-hook 'etags-select-mode-hook '(lambda () (local-unset-key (kbd "M-<return>"))))
(add-hook 'dired-mode-hook        '(lambda () (local-unset-key (kbd "C-o"))
                                              (local-unset-key (kbd "C-M-n"))
                                              (local-unset-key (kbd "C-M-p"))))

;; Mode specific keys
(define-key dired-mode-map (kbd "'") 'dired-up-directory)

