name: CICD

on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-setofskills.zshrc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: jakejarvis/s3-sync-action@v0.5.1 
        with:
          args: --acl public-read --content-type text/plain
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: 'setofskills.zshrc'
          DEST_DIR: 'setofskills.zshrc'
